import { Neucha } from "next/font/google";
import type { Metadata } from "next";
import "@/app/globals.css";
import Hydration from "@/app/hydration";
import { Providers } from "@/app/providers";

const neucha = Neucha({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' className='dark'>
			<body
				className={`${neucha.className} bg-gradient-to-br from-secondary-50 from-60%  to-secondary-400 to-100%  p-12`}
			>
				<Hydration />
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
